project:
  type: website
  output-dir: docs

website:
  title: "Saluscare Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Overview

format:
  dashboard:
    theme: cosmo
    css: styles.css